tunnel: 848f9056-284e-4755-b3eb-00afaea705b3
credentials-file: C:\Users\morga\.cloudflared\848f9056-284e-4755-b3eb-00afaea705b3.json
protocol: http2

ingress:
- hostname: api.mogges-store.se
  service: http://127.0.0.1:3000
- service: http_status:404
